blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jamaica-digital/jamaica/discussions
    about: Ask questions, share ideas, or discuss the project with the community.
